openapi: "3.0.0"
info:
  version: 1.0.0
  title: labofolio api
  license:
    name: MIT
servers:
  - url: https://local-api.labofolio.com
paths:
  /ping:
    $ref: './ref/ping.yaml#/paths/ping'
  /users:
    $ref: './ref/users.yaml#/paths/users'
  /users/{user_id}:
    $ref: './ref/users.yaml#/paths/user'

components:
  schemas:
    UserList:
      $ref: './ref/users.yaml#/components/schemas/UserList'
    User:
      $ref: './ref/users.yaml#/components/schemas/User'
    UserPayload:
      $ref: './ref/users.yaml#/components/schemas/UserPayload'
  parameters:
    limitQueryParams:
      $ref: './ref/common.yaml#/components/parameters/limitQueryParams'
    offsetQueryParams:
      $ref: './ref/common.yaml#/components/parameters/offsetQueryParams'
    userIdPathParams:
      $ref: './ref/common.yaml#/components/parameters/userIdPathParams'

tags:
  - name: system
    description: system relation api
  - name: users
    description: user api list