openapi: "3.0.0"
info:
  version: 1.0.0
  title: labofolio api
  license:
    name: MIT
servers:
  - url: https://local-api.labofolio.com
paths:
  ## system 監視
  /ping:
    $ref: './ref/ping.yaml#/paths/ping'

  ## 繋ぎ込みtest用
  /test:
    $ref: './ref/test.yaml#/paths/test'

tags:
  - name: system
    description: system relation api