openapi: "3.0.0"
info:
  version: 1.0.0
  title: labofolio api
  license:
    name: MIT
servers:
  - url: https://local-api.labofolio.com
paths:
  /ping:
    $ref: './ref/ping.yaml#/paths'
  /users:
    $ref: './ref/users.yaml#/paths'

components:
  schemas:
    UserList:
      $ref: './ref/users.yaml#/components/schemas/UserList'
    User:
      $ref: './ref/users.yaml#/components/schemas/User'

tags:
  - name: system
    description: system relation api
  - name: users
    description: user api list